try {
  var a = (1), b = (2);
  var c = a + b;
  console.log(d);
} catch (err) {
  alert (err.message);
}
